#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

# measurements
bspc config border_width            2
bspc config window_gap              0
bspc config split_ratio             0.50
bspc config top_padding             0
bspc config bottom_padding          0
bspc config right_padding           0
bspc config left_padding            0

# booleans
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

# colors
bspc config normal_border_color     "#191970"
bspc config focused_border_color    "#4672B4"

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

